export const data = {
    links: {
        image: "/sq-photo.jpeg",
        name: "Ahmed Saad",
        title: "software engineer & creator",
        socials: [
            {
                title: "LinkedIn",
                icon: "/logos/linkedin.png",
                darkicon: "/logos/linkedin-dark.png",
                link: "https://www.linkedin.com/in/saadsme/"
            },
            {
                title: "Twitter",
                icon: "/logos/twitter.png",
                darkicon: "/logos/twitter-dark.png",
                link: "https://twitter.com/saadds_"
            },
            {
                title: "TikTok",
                icon: "/logos/tiktok.png",
                darkicon: "/logos/tiktok-dark.png",
                link: "https://www.tiktok.com/@saads.me"
            },
            {
                title: "GitHub",
                icon: "/logos/github.png",
                darkicon: "/logos/github-dark.png",
                link: "https://www.github.com/saadsme"
            },
            {
                title: "Instagram",
                darkicon: "/logos/instagram-dark.png",
                icon: "/logos/instagram.png",
                link: "https://www.instagram.com/saads.me"
            }
        ],
        buttons: [
            // {
            //     text: "My Website",
            //     //icon: "/logos/website.png",
            //     link: "https://www.saads.me"
            // },
            {
                text: "Support my work!",
                //icon: "/logos/email.png",
                link: "https://shop.saads.me"
            },
            {
                text: "Work with me!",
                //icon: "/logos/email.png",
                link: "mailto:hello@saads.me"
            },
        ]
    },
    // "projects": {
    //     "title": "Projects | Ahmed Saad",
    //     "description": "Generated by create next app",
    //     "cards": [
    //     {
    //         "title": "Hello",
    //         "desc": "bello",
    //         "slug": "",
    //         "image": "",
    //         "categ": [
    //         "Android",
    //         "Java",
    //         "Firebase",
    //         "APIs"
    //         ],
    //         "href": ""
    //     }
    //     ]
    // },
    // "basicCard": {
    //     "title": "Hello",
    //     "date": "2021",
    //     "company": "Company",
    //     "points": [
    //     "point1",
    //     "point2",
    //     "point3"
    //     ]
    // }
    }