export const data = {
    links: {
        image: "/sq-photo.jpeg",
        name: "Ahmed Saad",
        title: "software engineer & creator",
        socials: [
            {
                title: "LinkedIn",
                icon: "/logos/linkedin.png",
                href: "https://www.linkedin.com/in/ahmed-saad-0b0b5b1a2/"
            },
            {
                title: "Twitter",
                icon: "/logos/twitter.png",
                href: "https://www.twitter.com/ahmedsaad1010"
            },
            {
                title: "TikTok",
                icon: "/logos/tiktok.png",
                href: "https://www.github.com/ahmedsaad1010"
            },
            {
                title: "GitHub",
                icon: "/logos/github-mark.svg",
                href: "https://www.github.com/ahmedsaad1010"
            },
            {
                title: "Instagram",
                icon: "/logos/instagram.png",
                href: "https://www.instagram.com/ahmedsaad1010"
            }
        ],
        buttons: [
            {
                text: "My Website",
                icon: "/logos/website.png",
                link: "https://www.saads.me"
            },
            {
                text: "Get my FREE Notion Task Managment Template",
                icon: "/logos/email.png",
                link: "https://shop.saads.me"
            },
            {
                text: "Work with me!",
                icon: "/logos/email.png",
                link: "mailto:hello@saads.me"
            },
        ]
    },
    // "projects": {
    //     "title": "Projects | Ahmed Saad",
    //     "description": "Generated by create next app",
    //     "cards": [
    //     {
    //         "title": "Hello",
    //         "desc": "bello",
    //         "slug": "",
    //         "image": "",
    //         "categ": [
    //         "Android",
    //         "Java",
    //         "Firebase",
    //         "APIs"
    //         ],
    //         "href": ""
    //     }
    //     ]
    // },
    // "basicCard": {
    //     "title": "Hello",
    //     "date": "2021",
    //     "company": "Company",
    //     "points": [
    //     "point1",
    //     "point2",
    //     "point3"
    //     ]
    // }
    }