import Head from 'next/head'

import {GraphQLClient, gql} from 'graphql-request'
import BlogCard from '/components/BlogCard.js'
import NavBar from '../components/NavBar';

const graphcms = new GraphQLClient("https://api-ap-south-1.hygraph.com/v2/clckiz8mj1fr101ukd1cqfzkm/master");

const QUERY = gql`
{
  posts {
    category
    createdAt
    id
    publishedAt
    publishedOn
    slug
    title
    updatedAt
    content {
      html
    }
    description
  }
}`;


export async function getStaticProps(){
  const {posts} = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({posts}) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <NavBar/>
        { posts.map((post) => (
          <BlogCard 
              title={post.title} 
              author={post.author} 
              datePublished={post.datePublished}
              slug={post.slug}
              description={post.description} />
        )
        )}
      </main>
    </>
  )
}
