import NavBar from "../components/NavBar";
import Footer from '../components/Footer';
import Head from 'next/head'
import ProjectCardLarge from "../components/legacy/ProjectCardLarge";
var categs1 = ['Android' , 'Java', 'Firebase', 'APIs']
export default function Projects(){
    return(
        <>
        <Head>
        <title>Projects | Ahmed Saad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/favicon.ico" />
      </Head>
        <div className='flex flex-col justify-center w-full max-w-4xl mx-auto mb-16'>
            <NavBar/>
            <div className="w-full">

            <ProjectCardLarge title="Hello" desc="bello" slug='' image='' categ={categs1} href=''/>        




            </div>
            <div className='mt-24 w-full'><Footer/></div>
        </div>
        </>
    )
}