import NavBar from "../components/NavBar";
import Footer from '../components/Footer';
import Head from 'next/head'

export default function Projects(){
    return(
        <>
        <Head>
        <title>Projects | Ahmed Saad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/favicon.ico" />
      </Head>
        <div className='flex flex-col items-start justify-center w-full max-w-2xl mx-auto mb-16'>
            <NavBar/>
            <div className="text-5xl font-bold justify-center">THIS PAGE IS UNDER CONSTRUCTION. THANK YOU!</div>
            <div className='mt-24 w-full'><Footer/></div>
        </div>
        </>
    )
}